import type { Metadata } from 'next'

import Header from '@/components/header'

import { roboto } from './fonts'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Header />
				<main className="mt-12">{children}</main>
			</body>
		</html>
	)
}
